---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: navitas-frontend-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/navitas-frontend" # Example path on the host node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navitas-frontend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: navitas-frontend
  name: navitas-frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: navitas-frontend
  template:
    metadata:
      labels:
        app: navitas-frontend
    spec:
      containers:
        - name: my-navitas-frontend
          image: 891377337960.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          volumeMounts:
            - name: navitas-frontend-storage
              mountPath: /app/data # Path inside the container where the volume will be mounted
      volumes:
        - name: navitas-frontend-storage
          persistentVolumeClaim:
            claimName: navitas-frontend-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: navitas-frontend
    k8s-app: navitas-frontend
  name: navitas-frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer
  selector:
    app: navitas-frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: navitas-frontend-pod
  labels:
    app: navitas-frontend
spec:
  containers:
    - name: my-navitas-frontend
      image: 891377337960.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      volumeMounts:
        - name: navitas-frontend-storage
          mountPath: /app/data # Path inside the container where the volume will be mounted
  volumes:
    - name: navitas-frontend-storage
      persistentVolumeClaim:
        claimName: navitas-frontend-pvc
